function [f] = f_k(mu, eta_hat, rho, k, K) %29
            f = 2*log(mu) + ...
            rho/2 * (K-k+1+1) * mu^2 - ...
            rho * sum(eta_hat(k:K+1)) * mu + ...
            rho/2 * sum(eta_hat(k:K+1).^2);
end