function [g] = g_k(varsigma, epsilon, rho, k) %39
    g = -2 * log(varsigma) + ...
    rho/2 * (k-1) * varsigma.^2 - ...
    rho * sum(epsilon(2:k)) * varsigma + ...
    rho/2 * sum(epsilon(2:k).^2);
end